// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace WEB_projekat.Migrations
{
    [DbContext(typeof(AutoSkolaContext))]
    partial class AutoSkolaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InstruktorVozilo", b =>
                {
                    b.Property<int>("ListaInstruktoraID")
                        .HasColumnType("int");

                    b.Property<int>("VozilaID")
                        .HasColumnType("int");

                    b.HasKey("ListaInstruktoraID", "VozilaID");

                    b.HasIndex("VozilaID");

                    b.ToTable("InstruktorVozilo");
                });

            modelBuilder.Entity("Models.Instruktor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GodinaRodjena")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Telefon")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Instruktor");
                });

            modelBuilder.Entity("Models.Polaznik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrLicneKarte")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("InstruktorID")
                        .HasColumnType("int");

                    b.Property<int>("JMBG")
                        .HasMaxLength(13)
                        .HasColumnType("int");

                    b.Property<bool>("PolozioTest")
                        .HasColumnType("bit");

                    b.Property<bool>("PolozioVoznju")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("VoziloID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("InstruktorID");

                    b.HasIndex("VoziloID");

                    b.ToTable("Polaznik");
                });

            modelBuilder.Entity("Models.Vozilo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Model")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("SnagaMotora")
                        .HasColumnType("int");

                    b.Property<int?>("VoziloID")
                        .HasColumnType("int");

                    b.Property<string>("VrstaVozila")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZapreminaMotora")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VoziloID");

                    b.ToTable("Vozilo");
                });

            modelBuilder.Entity("InstruktorVozilo", b =>
                {
                    b.HasOne("Models.Instruktor", null)
                        .WithMany()
                        .HasForeignKey("ListaInstruktoraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Vozilo", null)
                        .WithMany()
                        .HasForeignKey("VozilaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Polaznik", b =>
                {
                    b.HasOne("Models.Instruktor", "Instruktor")
                        .WithMany("Polaznici")
                        .HasForeignKey("InstruktorID");

                    b.HasOne("Models.Vozilo", "Vozilo")
                        .WithMany()
                        .HasForeignKey("VoziloID");

                    b.Navigation("Instruktor");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("Models.Vozilo", b =>
                {
                    b.HasOne("Models.Vozilo", null)
                        .WithMany("ListaVozila")
                        .HasForeignKey("VoziloID");
                });

            modelBuilder.Entity("Models.Instruktor", b =>
                {
                    b.Navigation("Polaznici");
                });

            modelBuilder.Entity("Models.Vozilo", b =>
                {
                    b.Navigation("ListaVozila");
                });
#pragma warning restore 612, 618
        }
    }
}
